// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	DISCORD_TOKEN: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_PUBLIC_KEY: string;
	DB: D1Database;
}
